# Generated by Django 5.1.6 on 2025-03-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="steps",
        ),
        migrations.AddField(
            model_name="recipe",
            name="method",
            field=models.TextField(default="No method"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(default="No ingredients"),
        ),
        migrations.DeleteModel(
            name="Step",
        ),
    ]
