# Generated by Django 5.1.7 on 2025-03-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="prep_time",
        ),
    ]
