# Generated by Django 5.1.6 on 2025-03-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_ingredients_remove_recipe_steps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                default="", help_text="Enter a description of your recipe here."
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="method",
            field=models.TextField(default=""),
        ),
    ]
