# Generated by Django 5.1.6 on 2025-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_description_alter_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
