# Generated by Django 5.1.6 on 2025-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_image_alter_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="recipe_images/"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(
                default="", help_text="Separate ingredients with commas."
            ),
        ),
    ]
