# Generated by Django 5.1.6 on 2025-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_image_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="media/recipe_images/"
            ),
        ),
    ]
