# Generated by Django 5.1.6 on 2025-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="media/uploads/"
            ),
        ),
    ]
