# Generated by Django 5.1.6 on 2025-03-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
        ),
    ]
