# Generated by Django 5.1.6 on 2025-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_recipe_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
        migrations.AddField(
            model_name="recipe",
            name="stars",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
