# Generated by Django 5.1.6 on 2025-03-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_cuisine_delete_hotel_recipe_stars_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="stars",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
