# Generated by Django 5.1.6 on 2025-03-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_alter_recipe_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="stars",
            field=models.PositiveIntegerField(),
        ),
    ]
