# Generated by Django 5.1.6 on 2025-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_alter_recipe_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="stars",
            field=models.PositiveIntegerField(help_text="number of stars"),
        ),
    ]
