# Generated by Django 5.1.6 on 2025-03-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_alter_recipe_stars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="stars",
        ),
    ]
