# Generated by Django 5.1.6 on 2025-03-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_remove_recipe_stars"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cuisine",
        ),
    ]
