# Generated by Django 5.1.6 on 2025-03-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0015_delete_cuisine"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="stars",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
