# Generated by Django 5.1.6 on 2025-03-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0017_cuisine"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cuisine",
            field=models.ManyToManyField(to="recipes.cuisine"),
        ),
    ]
