# Generated by Django 5.1.7 on 2025-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0018_recipe_cuisine"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakfast", "breakfast"),
                    ("lunch", "lunch"),
                    ("dinner", "dinner"),
                    ("dessert", "dessert"),
                    ("snack", "snack"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
